"use client";

import { useState, type SubmitEvent } from "react";
import { X } from "lucide-react";
import { roles as roleDefinitions } from "@/lib/roles";
import type { RoleId } from "@/lib/roles";
import { useAuthStore } from "@/store/auth-store";
import { useUsersStore, type Person, type AccountStatus } from "@/store/users-store";
import { AccessibleDialog } from "@/components/ui/accessible-dialog";
import { useCurrentUser } from "@/hooks/use-current-user";
import { useAdminStore } from "@/store/admin-store";

type PersonFormModalProps = {
  mode: "add" | "edit";
  initial?: Person;
  onClose: () => void;
  onSaved: (message: string) => void;
};

function validateInitialPassword(password: string) {
  const trimmed = password.trim();

  if (!trimmed) {
    return null;
  }

  if (trimmed.length < 8) {
    return "Initial password must be at least 8 characters.";
  }

  if (!/[A-Z]/.test(trimmed)) {
    return "Initial password must contain at least one uppercase letter.";
  }

  if (!/\d/.test(trimmed)) {
    return "Initial password must contain at least one number.";
  }

  return null;
}

export function PersonFormModal({ mode, initial, onClose, onSaved }: PersonFormModalProps) {
  const accessToken = useAuthStore((state) => state.accessToken);
  const addPerson = useUsersStore((state) => state.addPerson);
  const updatePerson = useUsersStore((state) => state.updatePerson);
  const people = useUsersStore((state) => state.people);
  const currentUser = useCurrentUser();
  const orgUnits = useAdminStore((state) => state.orgUnits);

  const [name, setName] = useState(initial?.name ?? "");
  const [email, setEmail] = useState(initial?.email ?? "");
  const [role, setRole] = useState<RoleId>(initial?.role ?? "scs");
  const [unit, setUnit] = useState(initial?.unitId ?? "");
  const [status, setStatus] = useState<AccountStatus>(initial?.status ?? "active");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [isSaving, setIsSaving] = useState(false);

  const canCreateAdminRole = currentUser?.roleName === "DWS Superadmin";
  const creatableRoles = roleDefinitions.filter((definition) => {
    if (definition.id === "plan") {
      return false;
    }

    if (definition.id === "admin" && !canCreateAdminRole) {
      return false;
    }

    return true;
  });
  const availableRoles =
    initial && !creatableRoles.some((definition) => definition.id === initial.role)
      ? roleDefinitions.filter((definition) => definition.id === initial.role || creatableRoles.some((allowed) => allowed.id === definition.id))
      : creatableRoles;

  const handleSubmit = async (e: SubmitEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!accessToken) {
      setError("Your session expired. Please sign in again.");
      return;
    }

    if (!name.trim() || !email.trim()) {
      setError("Name and email are required.");
      return;
    }

    if (mode === "add") {
      const passwordError = validateInitialPassword(password);
      if (passwordError) {
        setError(passwordError);
        return;
      }
    }

    const normalizedEmail = email.trim().toLowerCase();
    const duplicate = people.find(
      (p) => p.email === normalizedEmail && p.id !== initial?.id
    );
    if (duplicate) {
      setError("An account with this email already exists.");
      return;
    }

    setError("");
    setIsSaving(true);

    if (mode === "add") {
      const result = await addPerson(accessToken, { name, email, password, role, unit, status });
      setIsSaving(false);

      if (!result.ok) {
        setError(result.error || "Unable to add this person.");
        return;
      }

      onSaved(
        result.initialPassword
          ? `${name} added. Initial password generated by the backend is ready to share.`
          : `${name} added and assigned to ${role.toUpperCase()}.`,
      );
    } else if (initial) {
      const result = await updatePerson(accessToken, initial.id, { name, email, role, unit, status });
      setIsSaving(false);

      if (!result.ok) {
        setError(result.error || "Unable to update this person.");
        return;
      }

      onSaved(`${name}'s account updated.`);
    } else {
      setIsSaving(false);
      return;
    }

    onClose();
  };

  return (
    <AccessibleDialog
      open
      onClose={onClose}
      titleId="person-form-title"
      className="bg-white dark:bg-[#0e1628] rounded-2xl p-6 max-w-md w-full shadow-2xl"
    >
        <div className="flex items-center justify-between mb-4">
          <h3 id="person-form-title" className="text-sm font-bold text-slate-800 dark:text-white">
            {mode === "add" ? "Add person" : "Edit person"}
          </h3>
          <button
            onClick={onClose}
            aria-label="Close"
            className="text-slate-400 hover:text-slate-700 dark:hover:text-white cursor-pointer"
            type="button"
          >
            <X className="size-4" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-3">
          <div>
            <label htmlFor="person-name" className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Name</label>
            <input
              id="person-name"
              name="full_name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full rounded-lg border border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-[#070a13] px-3 py-2 text-sm text-slate-800 dark:text-white outline-none focus:border-[var(--brand-color)]"
              placeholder="Full name"
              disabled={isSaving || mode === "edit"}
            />
            {mode === "edit" && (
              <p className="mt-1 text-[10px] text-slate-400">Name is read-only here because the current admin API does not support profile-name edits.</p>
            )}
          </div>
          <div>
            <label htmlFor="person-email" className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Email</label>
            <input
              id="person-email"
              name="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full rounded-lg border border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-[#070a13] px-3 py-2 text-sm text-slate-800 dark:text-white outline-none focus:border-[var(--brand-color)]"
              placeholder="name@ascend.mil"
              disabled={isSaving || mode === "edit"}
            />
            {mode === "edit" && (
              <p className="mt-1 text-[10px] text-slate-400">Email is read-only here because the current admin API does not expose admin-side email edits.</p>
            )}
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label htmlFor="person-role" className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Role</label>
              <select
                id="person-role"
                name="role"
                value={role}
                onChange={(e) => setRole(e.target.value as RoleId)}
                className="w-full rounded-lg border border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-[#070a13] px-3 py-2 text-sm text-slate-800 dark:text-white outline-none focus:border-[var(--brand-color)]"
                disabled={isSaving}
              >
                {availableRoles.map((r) => (
                  <option key={r.id} value={r.id}>
                    {r.name}
                  </option>
                ))}
              </select>
              {mode === "add" && (
                <p className="mt-1 text-[10px] text-slate-400">
                  Provisioning uses the live `POST /admin/users` contract. `Plan` is not a real backend role, and `DWS Admin` creation requires a `DWS Superadmin`.
                </p>
              )}
            </div>
            <div>
              <label htmlFor="person-status" className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Status</label>
              <select
                id="person-status"
                name="status"
                value={status}
                onChange={(e) => setStatus(e.target.value as AccountStatus)}
                className="w-full rounded-lg border border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-[#070a13] px-3 py-2 text-sm text-slate-800 dark:text-white outline-none focus:border-[var(--brand-color)]"
                disabled={isSaving}
              >
                <option value="active">Active</option>
                <option value="deactivated">Deactivated</option>
              </select>
            </div>
          </div>
          <div>
            <label htmlFor="person-unit" className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Unit / team</label>
            <select
              id="person-unit"
              name="unit_id"
              value={unit}
              onChange={(e) => setUnit(e.target.value)}
              className="w-full rounded-lg border border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-[#070a13] px-3 py-2 text-sm text-slate-800 dark:text-white outline-none focus:border-[var(--brand-color)]"
              disabled={isSaving}
            >
              <option value="">No unit assigned</option>
              {orgUnits.map((orgUnit) => (
                <option key={orgUnit.id} value={orgUnit.id}>
                  {orgUnit.name}
                </option>
              ))}
              {initial?.unitId && !orgUnits.some((orgUnit) => orgUnit.id === initial.unitId) && (
                <option value={initial.unitId}>{initial.unit || initial.unitId}</option>
              )}
            </select>
            <p className="mt-1 text-[10px] text-slate-400">Uses the live admin org-unit catalog so assignments send the correct backend `unit_id` while showing the real unit name.</p>
          </div>

          {mode === "add" && (
            <div>
              <label htmlFor="person-password" className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-slate-400">
                Initial password
              </label>
              <div className="flex items-center gap-2">
                <input
                  id="person-password"
                  name="initial_password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full rounded-lg border border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-[#070a13] px-3 py-2 text-sm font-mono text-slate-800 dark:text-white outline-none focus:border-[var(--brand-color)]"
                  placeholder="Leave blank to let the backend decide"
                  disabled={isSaving}
                />
              </div>
              <p className="mt-1 text-[10px] text-slate-400">Optional. If left blank, the backend can return or manage the initial password according to its own rules.</p>
              <p className="mt-1 text-[10px] text-slate-400">If you enter one yourself, it must be 8+ characters and include at least 1 uppercase letter and 1 number.</p>
            </div>
          )}

          {error && <p className="text-xs font-medium text-rose-500">{error}</p>}

          <div className="flex items-center justify-end gap-2 pt-2">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 cursor-pointer"
              disabled={isSaving}
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSaving}
              className="px-4 py-2 bg-[var(--brand-color)] hover:bg-[var(--brand-color-hover)] disabled:opacity-60 text-white rounded-xl text-xs font-bold shadow-sm cursor-pointer"
            >
              {isSaving ? "Saving..." : mode === "add" ? "Add person" : "Save changes"}
            </button>
          </div>
        </form>
    </AccessibleDialog>
  );
}
